config/routes.rb
Hotfix::Application.routes.draw do
  root to: 'landings#show'

  get :project_files, to: 'project_files#index'
  get :project_file, to: 'project_files#show'
  patch :project_file, to: 'project_files#update'
end

app/models/project_file.rb
class ProjectFile
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :is_file, :full_path, :entries, :path, :content, :server, :old_content

  def initialize(attributes = {})
    return if attributes.nil?

    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def path=(string)
    @path = string
    @full_path = server.fixed_app_path + string
  end

  def persisted?
    true
  end

  def server
    @server ||= Server.new
  end

  def content
    return @content if @content

    file = server.get_file_content(full_path)
  end

  def content=(string)
    self.old_content = content
    @content = string.gsub("\r", '')
  end

  def save
    server.rewrite_file(full_path, content)
    server.restart

    true
  end

  def sort_criteria
    type = is_file ? '1' : '0'
    "#{type}#{name.downcase}"
  end
end

app/models/server.rb
require 'net/sftp'
require 'stringio'

class Server
  SERVER_OPTIONS = Hotfix::Application.config.server_options

  attr_accessor :host, :user, :password, :restart_command, :fixed_app_path, :port, :target_app

  def initialize(attributes = nil)
    (attributes || SERVER_OPTIONS).each do |name, value|
      send("#{name}=", value)
    end
  end

  def file_list(full_path)
    list = ''

    Net::SFTP.start(host, user, password: password, port: port) do |sftp|
      list = sftp.dir.entries(full_path).map{ |t| [t.name, t.file?] }
    end

    list
  end

  def restart
    Net::SSH.start(host, user, password: password, port: port) do |ssh|
      ssh.exec!(restart_command)
    end
  end

  def rewrite_file(full_path, content)
    Net::SFTP.start(host, user, password: password, port: port) do |sftp|
      io = StringIO.new(content)
      sftp.upload!(io, full_path)
    end
  end

  def get_file_content(full_path)
    content = ''

    Net::SFTP.start(host, user, password: password, port: port) do |sftp|
      sftp.file.open(full_path) do |file|
        content = file.read
      end
    end

    content
  end

  def list(path = '')
    path ||= ''
    inner_list(path).sort_by(&:sort_criteria)
  end

  def inner_list(current_path)
    list = []

    file_list([fixed_app_path, current_path].join('/')).sort{ |a,b| a[0].downcase <=> b[0].downcase }.each do |entry, is_file|
      next if (entry == '..' || entry == '.')
      entry_full_path = [fixed_app_path, current_path, entry].join('/')

      list << ProjectFile.new(name: entry, is_file: is_file, full_path: entry_full_path)
    end

    list
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from Net::SFTP::StatusException, with: :ssh_exception_hendler

  private

  def ssh_exception_hendler
    redirect_to root_path, alert: 'Sorry, server is experiencing problems with ssh connection, please try again later.'
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
end

app/controllers/project_files_controller.rb
class ProjectFilesController < ApplicationController
  before_filter :set_breadcrumbs
  before_filter :set_server
  before_filter :set_project_file, only: [:show, :update]

  def index
    @project_files = @server.list(params[:path])

  rescue
    ssh_exception_hendler
  end

  def show
  rescue
    ssh_exception_hendler
  end

  def update
    @project_file.content = params[:project_file][:content]

    if @project_file.save
      flash.now[:notice] = "Application successfully updated and now is restarting. Please check changes <a href='#{@server.target_app}' target='_blank' class='flash_link'>here</a>".html_safe
    else
      redirect_to :back, alert: "Something went wrong"
    end

  rescue
    ssh_exception_hendler
  end

  private

  def set_breadcrumbs
    @breadcrumbs = params[:path].split('/') if params[:path]
  end

  def set_server
    @server = Server.new(params[:server_options])
  end

  def set_project_file
    @dirs = params[:path].split('/')
    @project_file = ProjectFile.new(name: @dirs[-1], path: params[:path], server: @server)

    @project_files = @server.list(@dirs[0..-2].join('/'))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/project_files_helper.rb
module ProjectFilesHelper
  def parent_path(path, action)
    if action == 'index'
      project_files_path(path: path.split('/')[0..-2].join('/'))
    elsif path.split('/').size > 2
      project_files_path(path: path.split('/')[0..-3].join('/'))
    end
  end

  def entry_path(path, action, entry_name)
    if action == 'index'
      [path, entry_name].join('/')
    else
      [path.split('/')[0..-2], entry_name].flatten.join('/')
    end
  end
end

app/views/landings/show.html.slim
.description
  p Did you ever deploy your Rails app, waiting endless minutes for the specs to run, assets to precompile, unicorns to restart, only to find that you forgot to check for a nil somewhere?

  p Ouch, that hurts more than Sriracha!

  p Well, fear not, for we've got a solution for you:

  .buttons
    = link_to('Host HotFix on your server', 'https://github.com/railsrumble/r13-team-41', class: 'punch')
    | or
    = link_to('View Demo', :project_files, class: 'punch')

  .step.step_odd
    .step-image= image_tag('step1.png')
    .step-number Step 1
    .step-description Select the file that you want to fix

  .step.step_even
    .step-image= image_tag('step2.png')
    .step-number Step 2
    .step-description Fix that damn typo!

  .step.step_odd
    .step-image= image_tag('step3.png')
    .step-number Step 3
    .step-description Hit the "Update and Restart!"

  .step.step_even
    .step-image= image_tag('step4.png')
    .step-number Step 4
    .step-description That's it, the app is now fixed!

  .step-clear

  p This is a self-hosted solution, so you need to deploy it on your server and configure it for any app that you want to HotFix, but to show you the functionality, we hosted a demo application, that you can edit using the HotFix. This is  а Rails app created by Ryan Bates for his Railscasts (Ryan, thank you so much for what you're doing for RoR community) #{link_to('393 Guest User Record', 'https://github.com/railscasts/393-guest-user-record')}, you can access it on #{link_to('http://binarycode.r13.railsrumble.com:3000', 'http://binarycode.r13.railsrumble.com:3000')}. This is a real production app, running Unicorn, have fun playing with it and modifying it on the fly using HotFix!

  .hacker-note SPECIAL NOTE TO 1337 HAXORZ that will try to put <%- system "rm -rf ~/" %> in the erb templates and ruin everything: that is really not nice, and we should be nice like Matz is)). Anyway, the demo app is running in a docker container, and is reset to pristine untouched state every 10 minutes to prevent any defacing. Please bear that in mind while playing with the app, all your changes will be rolled back, so don't be mad))

  .buttons
    = link_to('Host HotFix on your server', 'https://github.com/railsrumble/r13-team-41', class: 'punch')
    | or
    = link_to('View Demo', :project_files, class: 'punch')

app/views/layouts/_flashes.slim
.flash-container
  - flash.each do |key, value|
    = content_tag(:div, value, class: "flash-message flash-message_#{key}")

app/views/layouts/application.html.slim
doctype html
html
  head
    title HotFix
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

  body class=(params[:screenshot] ? 'no-google-fonts' : '')
    #container
      = content_tag(:header, class: (controller_name != 'landings') && 'small') do
        = render('layouts/flashes')
        = link_to :root do
          h2= 'HotFix'
          = image_tag('cayenne3.png')
      = yield
    = javascript_include_tag('http://s0.railsrumble.com/banner.js')

app/views/project_files/_breadcrumbs.slim
.breadcrumbs
  .breadcrumbs-container
    .breadcrumbs-item
      = link_to(:project_files, class: 'breadcrumbs-item-link breadcrumbs-item-link_home') do
        = image_tag('icons/home.png')
    - if @breadcrumbs.present?
      - @breadcrumbs[1..-1].each_with_index do |item, index|
        .breadcrumbs-item.breadcrumbs-item_separator
          = image_tag('icons/next.png')
        .breadcrumbs-item
          - if (index + 2) == @breadcrumbs.size
            = item
          - else
            = link_to(item, project_files_path(path: @breadcrumbs[0..(index + 1)].join('/')), class: 'breadcrumbs-item-link')

app/views/project_files/_dashboard.slim
= render('breadcrumbs')

.dashboard
  .dashboard-container
    = render 'explorer'
    .editor= yield(:editor)
    .dashboard-clear

app/views/project_files/_explorer.slim
.explorer
  - unless params[:path].blank? || parent_path(params[:path], params[:action]).nil?
    .explorer-item
      = image_tag('icons/up.png', class: 'explorer-item-icon')
      = link_to '..', parent_path(params[:path], params[:action]), class: 'explorer-item-link'
  - @project_files.each do |item|
    .explorer-item
      = image_tag(item.is_file ? 'icons/file.png' : 'icons/folder.png', class: 'explorer-item-icon')
      - if item.is_file
        = link_to item.name, project_file_path(path: entry_path(params[:path], params[:action], item.name)), class: 'explorer-item-link'
      - else
        = link_to item.name, project_files_path(path: entry_path(params[:path], params[:action], item.name)), class: 'explorer-item-link'

app/views/project_files/_form.html.slim
= simple_form_for @project_file do |f|
  .editor-status
    = f.button :submit, 'Update and restart!', class: 'punch editor-update'
    .editor-status-content You are editing #{@project_file.name}
    .editor-status-content= link_to('View your application', @server.target_app, target: '_blank')
  = f.input :path, as: :hidden, input_html: { name: :path }
  = f.input :content, as: :text, label: false

app/views/project_files/index.html.slim
- content_for(:editor) do
  .quick-help
    p Your application is running at: #{link_to(@server.target_app, @server.target_app, target: '_blank')}

    p Please feel free to browse files and HotFix anything in your application. Don't forget to click "Update and restart!", this will update your files on remote server and restart the application runner!

= render('dashboard')

app/views/project_files/show.html.slim
- content_for(:editor) do
  .form
    = render 'form'

= render('dashboard')

app/views/project_files/update.html.slim
.diff-help
  .diff-help-inner Those are highlights of all the changes you've made to this file. Please do not forget to check them into your VCS!

.diff-outer
  .diff-container
    .diff-actions
      = link_to('Back to file list', :back, class: 'punch')

    = Diffy::Diff.new(@project_file.old_content.force_encoding('utf-8'), @project_file.content.force_encoding('utf-8')).to_s(:html).html_safe

    .diff-actions
      = link_to('Back to file list', :back, class: 'punch')